### 넘파이 배열
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자 수치 해석 프로그램에서는 numpy라고하는 배열 패키지를 사용함
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import
numpy 패키지를 사용하려면 먼저 패캐지를 설치해야 함
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야 함
```python
import numpy as np
```

In [91]:
import numpy as np

### 1차원 배열 만들기
넘파이의 `array` 함수를 사용하여 리스트를 `ndarray` 타입으로 변경 가능

In [92]:
ndarray_ = np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

In [93]:
type(ndarray_)

numpy.ndarray

In [94]:
floats = np.array([1.0, 2.0, 3.0])
floats

array([1., 2., 3.])

In [95]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름

In [96]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [97]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원

In [98]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 때
numbers = list(range(10))

result = []
for number in numbers:
    result.append(number * 2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [99]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [101]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))
numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [102]:
result = (numbers1 * 5) + numbers2
result

array([ 5, 11, 17, 23, 29])

In [103]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [104]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 > 2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()`의 매개변수로 전달하면 2차원 배열을 생성할 수 있음

In [105]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
len(numpy_matrix)

3

In [107]:
numpy_matrix[0]

array([1, 2, 3])

In [108]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원의 형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [109]:
three_d = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_tree_d = np.array(three_d)
numpy_tree_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
`ndim` : 배열의 차원을 정수로 반환
`shape`: 배열의 각 차원의 크기를 정수의 튜플로 반환

In [110]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [111]:
numpy_tree_d.ndim, numpy_tree_d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 `배열변수[인덱스]`의 형태로 사용함
다차원 형태일 경우는 일반 리스트와 다르게 `배열변수[인덱스, 인덱스, ...]`의 형태로 사용함
일반 2차원 리스트: `리스트[인덱스][인덱스]`
numpy 2차원 배열: `배열[인덱스, 인덱스]`

In [112]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [113]:
three_d[1][0][3]

16

In [114]:
# numpy 3차원 배열
numpy_tree_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [115]:
numpy_tree_d[1, 0, 3]

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]`와 동일함
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때, `,`를 써야하는 것에 주의

In [116]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
numpy_matrix[0, :2]

array([1, 2])

In [120]:
numpy_matrix[:2, 0]

array([1, 4])

In [121]:
numpy_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [122]:
numpy_tree_d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.
다음 행렬과 같은 행렬이 있다.
```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [123]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [124]:
m[1, 2]

7

In [125]:
m[-1, -1]

14

In [126]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1, 1:3]

array([6, 7])

In [127]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:, 2]

array([ 7, 12])

In [128]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
**팬시 인덱싱(fancy indexig)** 이라고 부르는 배열 인덱싱 기법이 존재함
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱
`True`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야 함

In [129]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [130]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [131]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [132]:
numpy_array[numpy_array % 1 ==0]

array([1, 2, 3, 4, 5, 6, 7, 8])

#### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된 배열을 인덱스로 전달하여  
해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [133]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
index_array = np.array([0, 2, 3])

In [135]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우 예외가 발생함

In [136]:
index_array = np.array([0, 2, 3, 6, 0, 2, 3, 6, 0, 2, 3, 6])

In [137]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

In [138]:
index_array = np.array([0, 2, 20])

In [139]:
numpy_array[index_array]

IndexError: index 20 is out of bounds for axis 0 with size 8

#### 다차원 배열에서 배열 인덱싱

In [ ]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [ ]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2, 1, 0], :]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

##### 파이썬으로 다음 연산을 수행한다.
다음 행렬과 같은 배열이 있다.
```python
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
​
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 이 배열에서 3의 배수를 찾아라.
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

### numpy 배열의 자료형
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음  
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype`속성으로 확인이 가능

In [ ]:
numpy_array = np.array([1, 2, 3])
numpy_array.dtype

dtype('int32')

In [ ]:
numpy_array = np.array([1.0, 2.0, 3.0])
numpy_array.dtype

dtype('float64')

In [ ]:
numpy_array = np.array(['1.0', '2.0', '3.0'])
numpy_array.dtype

dtype('<U3')

`array()` 함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨  
만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해주면 됨

##### dtype의 접두사
b : 불리언, i : 정수, f : 실수, U : 유니코드

In [ ]:
numpy_array = np.array(['1.0', '2.0', '3.0'], dtype='f')
numpy_array.dtype

dtype('float32')

In [ ]:
numpy_array

array([1., 2., 3.], dtype=float32)

### numpy에서 Inf와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf`, 0을 0으로 나누면 `nan`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`, `logspace`

#### zeros
크기가 정해져 있고 원소를 0으ㅗㄹ 초기화한 배열을 생성하는 함수

In [ ]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [ ]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2, 3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2, 3), dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype으로 문자열 (U)로 지정하게 되면 문자열의 길이가 초과하면 초과된 부분이 손실됨

#### ones
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수
`zeros` 함수와 사용법이 동일

In [ ]:
ones_array = np.ones((3, 2, 2), dtype='i')
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [ ]:
zeros_array = np.zeros_like(ones_array, dtype='f')
zeros_array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터'로 채워진 배열을 생성  
`zeros`, `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [ ]:
empty_array = np.empty((10, 10))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95237514e-310, 4.69362364e-322, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538347e-311,
        1.08538318e-311],
       [1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538347e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311],
       [1.08538318e-311, 1.08538347e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538347e-311],
       [1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538347e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311],
       [1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.08538318e-311, 1.08538318e-311, 1.08538318e-311,
        1.0

#### arange
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [ ]:
arange_array = np.arange(10, 50)
arange_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
arange_array = np.arange(50, 10, -1)
arange_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T` 속성으로 반환 받을 수 있음

In [ ]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
numpy_tree_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
numpy_tree_d.T # 2, 3, 4, -> 4, 3, 2

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

배열의 크기 변경  
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태의 변경하려 한다면 `reshape` 메서드를 사용하여 변경할 수 있음

In [ ]:
numpy_array = np.zeros(12)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
reshape_array = numpy_array.reshape(4, 3)
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
reshape_array = numpy_array.reshape(2, 6)
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape` 메서드에 하나의 인자로 -1을 넣게 되면 다른 인자들을 통해서 추론하여 지정

In [ ]:
reshape_array = numpy_array.reshape(6, -1)
reshape_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
reshape_array = numpy_array.reshape(3, 1, -1)
reshape_array

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

만약, `reshape` 메서드의 인자들의 곱의 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생 -1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 없는 경우면 에러가 발생

In [ ]:
reshape_array = numpy_array.reshape(5, 2)
reshape_array

ValueError: cannot reshape array of size 6 into shape (5,2)

In [ ]:
reshape_array = numpy_array.reshape(5, -1)
reshape_array

ValueError: cannot reshape array of size 6 into shape (5,newaxis)

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel` 메서드를 사용

In [ ]:
numpy_matrix = np.empty((3, 4))
numpy_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
numpy_array = numpy_matrix.flatten()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
numpy_array = numpy_matrix.ravel()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

배열 사용에서 주의할 점은 *길이가 5인 1차원 배열* 과 *5x1 인 2차원 배열*, *1x5 인 2차원 배열*은 서로 각각 다른 배열 (요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다른 배열)

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis` 속성으로 차원을 증가 시킬 수 있음

In [ ]:
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
newaxis_array = numpy_array[np.newaxis]
newaxis_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

배열 연결하기  
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법

`hstack` : 행의 수가 같은 두 개 이상의 배열을 연결  
`vstack` : 열의 수가 같은 두 개 이상의 배열을 연결  
`dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결  
`stack` : dstack 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결. 단, 연결 축을 개발자가 직접 지정  
`r_`: 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함  
`c_` : 행끼리 연결, 최소 2차원의 배열로 연결
`tile` : 하나의 배열을 여러번 반복하여 연결

In [ ]:
zeros_array = np.zeros((3, 4))
zeros_array 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((3, 2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [ ]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((2, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [ ]:
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
stack_array = np.stack([zeros_array, ones_array])
stack_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
stack_array = np.stack([zeros_array, ones_array], axis = 1)
stack_array

array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

In [ ]:
r_array = np.r_[zeros_array, ones_array]
r_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c_array = np.c_[zeros_array, ones_array]
c_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
tile_array = np.tile(zeros_array, 2)
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
tile_array = np.tile(zeros_array, (3, 2))
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

##### 파이썬으로 다음 연산을 수행한다.
``` python
지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

In [ ]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 2))
hstack_array = np.hstack([zeros_array, ones_array])

arange_array = np.arange(10, 151, 10)
reshape_array = arange_array.reshape(3, 5)

vstack_array = np.vstack([hstack_array, reshape_array])
tile_array = np.tile(vstack_array, (2,1) )

tile_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 2차원 그리드 포인트 생성
좌표값의 쌍을 (그리드 포인트)을 새엇ㅇ하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [ ]:
x = np.arange(3)
x

array([0, 1, 2])

In [ ]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [ ]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음

In [ ]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [ ]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
    z[index] = x[index] + y[index]

CPU times: total: 0 ns
Wall time: 2.99 ms


In [ ]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [ ]:
x = np.arange(5)
y = np.arange(10, 15)
z = np.arange(5)

In [ ]:
np.all(x == y)

False

In [ ]:
np.all(x == z)

True

In [ ]:
np.all(x <= y)

True

In [ ]:
x

array([0, 1, 2, 3, 4])

In [ ]:
x * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
10 ** x

array([    1,    10,   100,  1000, 10000], dtype=int32)

### 브로드 캐스팅
차원이 서로 다른 배열을 연산하는 기능, 부족한 차원에 대하여 반복 확장하여 큰 배열의 크기에 맞춘 후 연산을 진행

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
x = np.arange(15)
x = x.reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

y = np.arange(3)
y = y.reshape(3, 1)
y

In [ ]:
x + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
x + y

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

### 차원 축소 연산
배열의 하나의 행을 하나의 집합으로 보고 그 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [ ]:
x = np.arange(10)
x = x.reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x.max()

9

In [ ]:
x.min()

0

In [ ]:
x.mean()

4.5

In [ ]:
x.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [ ]:
x.sum(axis=1)

array([10, 35])

### 정렬  
`sort` 메서드로 배열을 정렬 할 수 있음  
`axis` 매개변수로 정렬 기준을 정할 수 있음  
`axis=0` : 행을 따로 분리하여 정렬  
`axis=1` : 열을 따로 분리하여 정렬  
`axis`를 지정하지 않으면 가장 나중 차원을 기준으로 정렬

In [ ]:
x = np.array([
[5, 2, 7, 4],
[11, 8, 6, 5],
[8, 5, 11, 2]
])

x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  5],
       [ 8,  5, 11,  2]])

In [ ]:
x.sort()
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [ ]:
x.sort(axis=0)
x

array([[ 5,  2,  6,  2],
       [ 8,  5,  7,  4],
       [11,  8, 11,  5]])

In [ ]:
x.sort(axis=1)
x

array([[ 2,  2,  5,  6],
       [ 4,  5,  7,  8],
       [ 5,  8, 11, 11]])

In [ ]:
np.argsort(x, axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int64)

넘파이로 다음 연산을 수행한다.  

실수로 이루어진 2 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.  

1. 전체의 최댓값  
2. 각 행의 합  
3. 각 행의 최댓값  
4. 각 열의 평균  
5. 각 열의 최솟값

In [ ]:
x = np.array([
    [5, 11, 12],
    [0, 18, 22],
    [8, 2, 7]
    ])
x

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 8,  2,  7]])

In [ ]:
# 전체의 최댓값
x.max()


22

In [ ]:
# 각 행의 합
x.sum(axis=1)

array([28, 40, 17])

In [ ]:
# 각 행의 최댓값
x.max(axis=1)

array([12, 22,  8])

In [ ]:
# 각 열의 평균
x.mean(axis=0)

array([ 4.33333333, 10.33333333, 13.66666667])

In [ ]:
# 각 열의 최솟값
x.min(axis=0)

array([0, 2, 7])

### Numpy 배열 통계 연산
- 데이터 개수 구하기 : `len()` 내장 함수
- 표본 평균 : `mean()` 메서드
- 표본 분산 : `var()` 메서드
- 표본 표준편차 : `std()` 메서드
- 최대, 최소 : `max()`, `min()` 메서드
- 중앙값 : `median()` 메서드
- 사분위수 : `percentile()` 메서드

In [ ]:
samples = np.array([9, 2, 4, 20, 24, 2, 23, 92, 24, -23])
samples.sort()
samples

array([-23,   2,   2,   4,   9,  20,  23,  24,  24,  92])

In [ ]:
sample_voume = len(samples)
sample_voume

10

In [ ]:
sample_mean = samples.mean()
sample_mean

17.7

In [ ]:
sample_mean = np.mean(samples)
sample_mean

17.7

In [ ]:
sample_voume = samples.var()
sample_voume

804.61

In [ ]:
sample_voume = np.var(samples)
sample_voume

804.61

In [ ]:
sample_standard = samples.std()
sample_standard

28.365648238670662

In [ ]:
sample_standard = np.std(samples)
sample_standard

28.365648238670662

In [ ]:
sample_max = np.max(samples)
sample_max

92

In [ ]:
sample_min = samples.min()
sample_min

-23

In [ ]:
sample_median = np.median(samples)
sample_median

14.5

In [ ]:
sample_0per = np.percentile(samples, 0)
sample_0per

-23.0

In [ ]:
sample_25per = np.percentile(samples, 25)
sample_25per

2.5

In [ ]:
sample_50per = np.percentile(samples, 50)
sample_50per

14.5

In [ ]:
sample_75per = np.percentile(samples, 75)
sample_75per

23.75

In [ ]:
sample_100per = np.percentile(samples, 100)
sample_100per

92.0

### 난수 생성에 필요한 시드 설정
numpy 패키지에 있는 `seed()` 메서드에 매개변수로 난 수 생성시 필요한 시드를 설정함

In [ ]:
np.random.seed(10)

In [ ]:
random_array = np.random.rand(10)
random_array

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

### 데이터 순서를 임의로 바꾸기
numpy 패키지의 random 하위 패키지의 `suffle()`메서드로 배열을 임의 순서로 변경 가능(자체 변환)

In [ ]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(range_array)
range_array

array([1, 6, 2, 5, 7, 8, 9, 0, 3, 4])

### 데이터 샘플링
모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는 방법  
numpy 패키지의 random 하위패키지의 `choice(모집단배열, 표본크기, 중복선택여부, 각요소의선택확률배열)` 메서드로 사용 가능

In [ ]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sample_array = np.random.choice(population_array, 5)
sample_array

array([5, 8, 9, 8, 5])

In [ ]:
sample_array = np.random.choice(population_array, 5, replace=False)
sample_array

array([3, 0, 1, 2, 6])

In [ ]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
sample_array = np.random.choice(population_array, 1000, p=probability_array)
sample_array

In [ ]:
sample_array = np.random.choice(population_array, 12, replace=False)
sample_array # 오류

In [ ]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.25]
sample_array = np.random.choice(population_array, 1000, p=probability_array)
sample_array # 오류

### 난수 배열 생성
- `rand()`: 0과 1사이의 균일 분포를 따르는 난수 배열 생성
- `randn()`: 표준 정규 분포를 따르는 난수 배열 생성
- `randint(low, high=정수, size=정수혹은튜플)`: 지정한 범위의 정수의 균일 분포를 따르는 난수 배열 생성

In [ ]:
random_array = np.random.rand(10)
random_array

array([0.26685576, 0.77733783, 0.09475754, 0.27389181, 0.12651792,
       0.42464669, 0.16477692, 0.65249946, 0.05259622, 0.48449566])

In [ ]:
randn_array = np.random.randn(10)
randn_array

array([-0.94531276,  0.72054254, -1.63272143,  1.03374421, -0.03882343,
        0.29915121, -1.27309222, -0.86876804, -0.41363047, -0.13425236])

In [ ]:
randint_array = np.random.randint(10)
randint_array

8

In [ ]:
randint_array = np.random.randint(10, size=10)
randint_array

array([3, 9, 8, 9, 7, 2, 9, 8, 0, 9])

In [ ]:
randint_array = np.random.randint(10, high=20, size=10)
randint_array

array([15, 19, 12, 19, 15, 14, 17, 15, 16, 11])

In [ ]:
randint_array = np.random.randint(10, high=20, size=(3, 5))
randint_array

array([[13, 16, 14, 11, 12],
       [18, 12, 14, 17, 16],
       [17, 16, 19, 19, 13]])

### 정수 데이터 카운팅
배열의 요소가 정수이면 `unique()` 메서드나 `bincount()` 메서드로 간단하게 분석할 수 있음

In [ ]:
analysis_array = np.unique(sample_array)
analysis_array

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [ ]:
analysis_array = np.unique(sample_array, return_counts=True)
analysis_array

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([ 98,  48,  47, 163, 257, 118,  53,  44, 172], dtype=int64))

In [ ]:
analysis_array = np.bincount(sample_array, minlength=10)
analysis_array

array([ 98,  48,  47,   0, 163, 257, 118,  53,  44, 172], dtype=int64)

### 파이썬으로 다음 연산을 수행한다.
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [ ]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
coin_simulation = np.random.randint(2, size=10)
coin_simulation

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [ ]:
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
dice_simulation = np.random.randint(1, high=7, size=100)
dice_simulation_mean = dice_simulation.mean()
dice_simulation_mean

3.3

### 파이썬으로 다음 연산을 수행한다.

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.  
250일 동안의 주가를 무작위로 생성하라

In [141]:
price = 10000

variation_ranges = (np.random.randn(250) / 100) + 1
variation_ranges

array([0.97993427, 0.99596475, 0.994653  , 1.00762171, 0.9948739 ,
       0.98357611, 0.99288126, 1.01476553, 1.0117604 , 0.99130827,
       1.00322042, 0.99396999, 0.99486507, 1.00235395, 1.00853655,
       1.01243205, 1.00653403, 0.98818904, 0.98320914, 0.99246364,
       1.02125036, 1.00326786, 1.00658818, 1.01119175, 1.00247624,
       1.00359119, 0.98315136, 0.99972202, 1.00477997, 1.01093361,
       0.99887015, 0.991423  , 0.9878026 , 0.9851101 , 0.99446772,
       0.996164  , 0.9844556 , 0.99299622, 1.0024899 , 1.0016326 ,
       0.99253   , 0.99318953, 1.00782948, 1.00497778, 1.0089468 ,
       0.99058242, 1.00176963, 0.98480336, 1.01386098, 1.00219195,
       1.00277552, 1.00622491, 0.98586166, 1.00143007, 0.99638577,
       0.99884582, 1.00624425, 0.99360575, 1.00019467, 1.01269255,
       0.9804467 , 0.9955241 , 0.9633374 , 1.00078943, 0.99209866,
       1.00212171, 0.97984158, 1.0173889 , 0.99302069, 0.98686045,
       0.998733  , 1.00079653, 0.9933493 , 0.98711069, 0.98732

In [142]:
stock_prices = []

for ratio in variation_ranges:
    price = round(price * round(ratio, 4))
    stock_prices.append(price)

stock_price_array = np.array(stock_prices)
stock_price_array

array([ 9799,  9760,  9708,  9782,  9732,  9572,  9504,  9645,  9759,
        9674,  9705,  9647,  9598,  9621,  9703,  9823,  9887,  9770,
        9606,  9534,  9737,  9769,  9833,  9943,  9968, 10004,  9836,
        9833,  9880,  9988,  9977,  9891,  9770,  9624,  9571,  9535,
        9387,  9321,  9344,  9359,  9289,  9226,  9298,  9344,  9427,
        9338,  9355,  9213,  9341,  9362,  9388,  9446,  9313,  9326,
        9292,  9281,  9339,  9279,  9281,  9399,  9215,  9174,  8837,
        8844,  8774,  8792,  8614,  8764,  8703,  8589,  8578,  8585,
        8527,  8417,  8310,  8361,  8251,  8200,  8342,  8382,  8271,
        8247,  8228,  8239,  8326,  8243,  8234,  8404,  8348,  8315,
        8327,  8375,  8490,  8588,  8611,  8528,  8325,  8347,  8390,
        8398,  8531,  8487,  8548,  8609,  8563,  8580,  8535,  8377,
        8421,  8420,  8325,  8490,  8540,  8488,  8432,  8558,  8522,
        8561,  8621,  8689,  8667,  8670,  8622,  8669,  8700,  8665,
        8805,  8575,